name: example
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  fields_generator:
    path: ../

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^2.4.7
  json_serializable: ^6.9.4
