name: fields_generator
version: 0.1.3
description: Fields name generator for Dart
homepage: https://github.com/masreplay/fields_generator

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  build: ^2.4.2
  source_gen: ^2.0.0
  analyzer:

  json_annotation: ^4.9.0
  change_case: ^2.2.0
  source_helper: ^1.3.5

dev_dependencies:
  build_runner: ^2.4.15
  grinder: ^0.9.5
